spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/reservation
    username: reservation
    password: MANAGER1
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:  
      ddl-auto: update #Change with update in producction
    generate-ddl: true #Replace with false in producction
    show-sql: true #Replace with false in producction
server:
  port: 8090 #You can configure another port